# Conclusion
## Main takeways of our exploration
1) By chloropleth maps, we discovered that the states with most number of deaths in the US are California (with about 900,000 deaths reported), Texas (with about 700,000 deaths reported) and Florida (with about 500,000 deaths reported). For the year of 2021 and 2022, states have the similar death distribution as the total deaths in the 3 years period.  
2) In 2020, 2021, 2022 and 2020-2022, the death distribution in each state by condition groups remained basically consistent. Among various condition groups, people with COVID-19 only, respiratory diseases and circulatory diseases suffered the most. This reminds us putting more emphasize on people with these three condition groups.  
3) Except obesity, people with ages 45+ take up about more than 90% in those deaths reported. Among them, for people with alzheimer disease and vascular and unspecified dementia, more than half of the death cases are in age group of 85+. For other conditions, 4 age groups between 55 and 85+ each take up about 20%. For people with obesity, only about less than 5% of the death patients are 85+. In conclusion, people older than 55 are more likely to experience severe symptoms, thus dying from COVID-19.  
4) Respiratory diseases and circulatory diseases are two major condition groups in death cases. From 2020 to 2022, the distribution of sub-conditions under them remains nearly the same. In respiratory diseases, influenza and adult respiratory distress syndromes are major conditions. In circulatory diseases, the distribution of sub-conditions is much more even and hypertensive diseases is the major condition.  
5) In the past three years, approximately 500,000 COVID-19 deaths were among people with respiratory diseases. Among them, 200,000 deaths cases were conditioned by influenza and pneumonia, and 170,000 death cases were conditioned by respiratory failures.  
6) The number of fatal cases for elder age groups can be more than hundred times the one for younger age groups, showing that elder groups are more vulnerable to COVID-19. Besides, from 2020 to 2022, the situation first got worse in 2021 and then got better in 2022. The reason behind could be effective prevention methods and virus mutations.  
7) In the past 3 years, there were 4 peaks for the entire United States. They came in 2020-05, 2021-02, 2021-10 and 2022-02 respectively.  
8) Most states have a similar trend of COVID-19 death cases as the one for the entire United States. States that went through a peak in the early stage of COVID-19 burst (around March 2020) are mainly in the east coast.  

## Limitations
1) Due to the large size of the data, memory of our computers is not enough for us to some graphs which may provide us with more insight. For instance, we are unable to plot heatmap during the missing value analysis.  
2) In some charts, since there are too many elements and the value of each element differs greatly, it is hard for readers to obtain complete information on stationary plots.    

## Future directions
To help readers grasp information in those graphs more accurately and conveniently, we would like to integrate those graphs into a huge interactive one. Readers can get access to different charts of each state and the whole country by merely click on the mouse. Besides, for easier comparison, readers are allowed to select multiple states at the same time so that they can see their disparities more directly.  

## Lessons learned
Through the project, we have truly experienced the whole process of EDAV from proposal, to data collection, to data cleaning/transformation, to missing value analysis and to data analysis. During data analysis, we have learned to choose the best visualization plots for our analysis purpose. In this case, we have utilized chloropleth maps, horizontal stacked bar charts, scatter plots, mosaic plots, heat maps and geo-facets. The interactive design part offers us with an opportunity to explore the importance of d3 interaction. In this case, we utilize d3 to make our last graph interactive, which is a geo-facet plot regarding the death-date curve of each state. The interaction design enabled us to integrate specific data values into each plot since the plotting space increased. Therefore, more accurate information can be acquired through the graph.